(() => {
'use strict';
const $=id=>document.getElementById(id), keys=new Set(), scene=new THREE.Scene();
let renderer,world,camera,player,body,legL,legR,armL,armR,ring,marker,mode='intro',pausedFrom='intro',elapsed=0,exposure=0,crouching=false,alerted=false,smokeSeconds=0,standingSmoke=0,fireSeconds=0,moved=0,quizCorrect=false,toastUntil=0,last=performance.now(),uiTick=0,muted=true,audioContext=null,quizAnswered=false,detour=false;
const state={x:0,z:17},counters={sessions:0};
const safeSources='<div class="sources">학습 근거: <a href="https://wj119.gwd.go.kr/egf/bp/board/article/download?fileSeq=1233816" target="_blank" rel="noopener">원주소방서 화재 행동요령</a> · <a href="https://www.seosan.go.kr/DATA/bbs/127/2025093003292192369karR.pdf" target="_blank" rel="noopener">소방청 국민행동요령</a></div>';
function fatal(error){$('fatal').hidden=false;$('fatal-detail').textContent=error?.message||'WebGL 초기화 실패';$('start').disabled=true;console.error(error);}
try {
 renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;renderer.setClearColor(0x121e25);$('scene').appendChild(renderer.domElement);
 scene.fog=new THREE.FogExp2(0x18252c,.007);scene.add(new THREE.HemisphereLight(0xd5e7ff,0x575143,2.4));const sun=new THREE.DirectionalLight(0xffe8c7,3.4);sun.position.set(-20,40,25);scene.add(sun);const rim=new THREE.DirectionalLight(0x83c4ef,1.6);rim.position.set(20,15,-30);scene.add(rim);
 camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.1,220);world=createWarehouseWorld(THREE,scene);
 player=new THREE.Group();body=new THREE.Group();player.add(body);scene.add(player);
 const mat=c=>new THREE.MeshLambertMaterial({color:c});const navy=mat(0x183847),orange=mat(0xff873a),skin=mat(0xe7bc8e),white=mat(0xeffacb),black=mat(0x142027);
 function part(w,h,d,m,x,y,z,parent=body){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);mesh.position.set(x,y,z);parent.add(mesh);return mesh;}
 part(.65,.82,.37,orange,0,1.14,0);part(.69,.09,.4,white,0,1.11,0);part(.48,.45,.42,skin,0,1.78,0);part(.64,.15,.57,white,0,2.04,0);part(.5,.14,.5,white,0,2.16,0);part(.38,.1,.02,black,0,1.82,-.215);
 legL=part(.22,.65,.27,navy,-.19,.44,0);legR=part(.22,.65,.27,navy,.19,.44,0);armL=part(.19,.72,.22,orange,-.46,1.17,0);armR=part(.19,.72,.22,orange,.46,1.17,0);
 const ringMesh=new THREE.Mesh(new THREE.RingGeometry(.7,.82,36),new THREE.MeshBasicMaterial({color:0xbdf5dc,side:THREE.DoubleSide,transparent:true,opacity:.8,depthWrite:false}));ringMesh.rotation.x=-Math.PI/2;ringMesh.position.y=.035;player.add(ringMesh);ring=ringMesh;
 const markerCanvas=document.createElement('canvas');markerCanvas.width=256;markerCanvas.height=96;const mctx=markerCanvas.getContext('2d');mctx.fillStyle='#102a34';mctx.beginPath();mctx.roundRect(30,5,196,63,14);mctx.fill();mctx.fillStyle='#d8ffee';mctx.font='bold 26px sans-serif';mctx.textAlign='center';mctx.fillText('YOU  ·  나',128,48);mctx.beginPath();mctx.moveTo(117,66);mctx.lineTo(139,66);mctx.lineTo(128,83);mctx.fill();marker=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(markerCanvas),depthTest:false}));marker.scale.set(2.1,.79,1);marker.position.y=3;player.add(marker);
 player.position.set(state.x,0,state.z);$('start').disabled=false;$('start').innerHTML='탈출 훈련 시작 <span>↗</span>';resize();requestAnimationFrame(frame);
}catch(error){fatal(error);return;}
function beep(freq=660,duration=.12){if(muted)return;try{audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type='sine';osc.frequency.value=freq;gain.gain.setValueAtTime(.04,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+duration);osc.connect(gain);gain.connect(audioContext.destination);osc.start();osc.stop(audioContext.currentTime+duration);}catch{}}
function toast(message,seconds=4){$('toast').textContent=message;$('toast').classList.add('show');toastUntil=performance.now()+seconds*1000;}
function closeModal(){$('modal').hidden=true;keys.clear();}
function showModal(html){keys.clear();$('dialog').innerHTML=html;$('modal').hidden=false;$('dialog').focus();}
function start(){closeModal();mode='playing';elapsed=0;exposure=0;crouching=false;alerted=false;smokeSeconds=0;standingSmoke=0;fireSeconds=0;moved=0;quizCorrect=false;quizAnswered=false;detour=false;world.alarm.active=false;counters.sessions++;state.x=0;state.z=17;player.position.set(0,0,17);body.rotation.set(0,0,0);$('intro').hidden=true;$('hud').hidden=false;document.body.classList.add('playing');$('crouch').classList.remove('active');$('crouch').setAttribute('aria-pressed','false');$('alert').textContent='E  “불이야!”';toast('초록색 비상구를 따라 이동하세요. 불길과 짙은 연기는 우회하세요.',6);updateUI();beep();}
function toggleCrouch(){if(mode!=='playing')return;crouching=!crouching;$('crouch').classList.toggle('active',crouching);$('crouch').setAttribute('aria-pressed',String(crouching));toast(crouching?'낮은 자세로 이동합니다. 그래도 짙은 연기에는 들어가지 마세요.':'일어섰습니다. 연기와 불길이 없는 경로를 찾으세요.',3);updateUI();}
function raiseAlert(){if(mode!=='playing')return;if(alerted){toast('주변에 알렸습니다. 대피를 계속하세요.',2);return;}alerted=true;const near=Math.hypot(state.x-world.alarm.x,state.z-world.alarm.z)<3;if(near)world.alarm.active=true;toast(near?'비상벨 작동 · “불이야!” 주변에 알렸습니다. 대피를 계속하세요.':'“불이야!” 주변에 알렸습니다. 대피를 계속하세요.',4);$('alert').textContent='✓ 주변에 알림';beep(880,.25);}
function pause(){if(mode==='playing'){mode='paused';showModal('<span class="micro">SIMULATION PAUSED</span><h2 id="dialog-title">잠시 멈췄습니다</h2><p>훈련 시간과 위험 노출도 함께 멈춥니다.<br>초록색 출구 표시와 안내도에서 다음 경로를 확인하세요.</p><button id="resume" class="primary">계속하기 <span>→</span></button><button id="restart" class="secondary">처음부터</button>');$('resume').onclick=resume;$('restart').onclick=start;}else if(mode==='paused')resume();}
function resume(){closeModal();mode='playing';}
function help(){if(mode==='help')return;pausedFrom=mode;mode='help';showModal('<span class="micro">HOW TO PLAY</span><h2 id="dialog-title">출구까지, 안전한 판단으로.</h2><ul><li><kbd>W A S D</kbd> 또는 <kbd>방향키</kbd> : 이동</li><li><kbd>C</kbd> : 낮은 자세 켜기 / 끄기</li><li><kbd>E</kbd> : 이동하면서 “불이야!” 알리기</li><li><kbd>Esc</kbd> : 일시정지 / 계속하기</li><li>모바일: 화면 방향 버튼과 자세 버튼 사용</li></ul><p>초록색 비상구를 통과해 옥외 집결지에 도착하면 탈출 성공입니다. 물건을 가져오거나 경보기를 누르러 돌아갈 필요가 없습니다.</p><p>연기 구간을 우회하는 것이 먼저입니다. 낮은 자세도 연기 속 안전을 보장하지 않습니다. 대피로가 막혔다면 불과 연기에서 떨어져 구조를 요청하세요.</p><p class="fineprint">위험 노출과 시간은 게임 지표이며 실제 생존 시간·호흡 상태를 예측하지 않습니다. 실제 대피는 현장 안내와 119 지시에 따르세요.</p><button id="help-close" class="primary">확인 <span>→</span></button>'+safeSources);$('help-close').onclick=()=>{closeModal();mode=pausedFrom;};}
function formatTime(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(Math.floor(s%60)).padStart(2,'0');}
function complete(){mode='quiz';keys.clear();$('damage').style.opacity='0';beep(880,.25);showModal('<span class="micro">EVACUATION COMPLETE · 대피 완료</span><h2 id="dialog-title">안전한 밖에 도착했습니다.</h2><p>이제 집결지에서 인원을 확인하고 119에 신고하세요.<br><b>어떤 신고가 가장 도움이 될까요?</b></p><div class="choices"><button data-answer="correct">① 위치·동/층·화재 상황·사람의 마지막 확인 위치를 알리고, 질문에 답한다.</button><button data-answer="wrong">② “쿠팡에 불이 났어요!”라고만 말하고 바로 끊는다.</button><button data-answer="wrong">③ 상황을 정확히 알아보기 위해 다시 창고 안으로 들어간다.</button></div><p id="quiz-feedback" aria-live="polite"></p><button id="see-result" class="primary" hidden>훈련 결과 보기 <span>→</span></button><p class="fineprint">이 게임은 실제로 119에 전화를 걸지 않습니다.</p>');document.querySelectorAll('[data-answer]').forEach(btn=>btn.onclick=()=>{if(quizAnswered)return;quizAnswered=true;quizCorrect=btn.dataset.answer==='correct';btn.classList.add(quizCorrect?'correct':'wrong');document.querySelectorAll('[data-answer]').forEach(b=>{b.disabled=true;if(b.dataset.answer==='correct')b.classList.add('correct');});$('quiz-feedback').textContent=quizCorrect?'좋은 판단입니다. 모르는 정보는 추측하지 말고 상황요원의 질문에 답하세요.':'①이 올바른 신고입니다. 확인한 위치와 상황을 설명하고, 다시 들어가지 마세요.';$('see-result').hidden=false;});$('see-result').onclick=()=>result(true);}
function result(success){mode='result';keys.clear();const routeScore=Math.max(0,40-Math.round(exposure*.4)),score=success?40+routeScore+(quizCorrect?20:0):0;const routeText=smokeSeconds<.1?'연기 구간을 피해 이동했습니다.':standingSmoke>.5?'서 있는 동안 연기에 노출되었습니다. 다음에는 연기 없는 경로를 먼저 찾으세요.':'낮은 자세로 이동했지만 연기 노출은 남습니다. 연기 구간 우회가 우선입니다.';showModal('<span class="micro">'+(success?'TRAINING REPORT':'RETRY THE ROUTE')+'</span><h2 id="dialog-title">'+(success?'탈출 완료. 판단을 돌아볼 시간.':'위험 노출로 훈련을 중단했습니다.')+'</h2><p>'+(success?'집결지에 도착했습니다. 실제 상황에서도 다시 들어가지 마세요.':'불길이나 연기 속에 머물면 위험합니다. 다음에는 위험 구역을 크게 우회해 보세요.')+'</p><div class="score-row"><div>안전 점수<b>'+score+'<small> /100</small></b></div><div>진행 시간<b>'+formatTime(elapsed)+'</b></div><div>위험 노출<b>'+Math.round(exposure)+'</b></div></div><div class="debrief"><p><strong>'+(success?'✓':'○')+' 대피 완료</strong> · '+(success?'비상구 → 옥외 집결지 도착':'집결지까지 안전한 경로를 다시 찾아보세요.')+'</p><p><strong>안전 경로</strong> · '+routeText+'</p><p><strong>주변 알림</strong> · '+(alerted?'이동 중 화재를 알렸습니다.':'가능하면 이동하면서 “불이야!”라고 알리세요. 알리기 위해 돌아갈 필요는 없습니다.')+'</p><p><strong>119 신고</strong> · '+(success?(quizCorrect?'위치와 상황을 전달하는 방법을 선택했습니다.':'위치·화재 상황·사람의 마지막 확인 위치를 알리고 질문에 답하세요.'):'안전한 장소에서 위치와 화재 상황을 알리세요.')+'</p></div><p class="fineprint">점수: 집결지 도착 40 + 위험 노출 최소화 최대 40 + 신고 판단 20. 속도와 알림 여부는 점수에 영향을 주지 않습니다. 실제 화재·인체 반응을 계산하는 시뮬레이터가 아닙니다.</p><button id="again" class="primary">다시 훈련하기 <span>↗</span></button><button id="back" class="secondary">첫 화면</button>'+safeSources);$('again').onclick=start;$('back').onclick=home;}
function home(){closeModal();mode='intro';keys.clear();$('intro').hidden=false;$('hud').hidden=true;$('damage').style.opacity='0';document.body.classList.remove('playing');state.x=0;state.z=17;player.position.set(0,0,17);body.scale.y=1;crouching=false;}
function blocked(x,z){if(x< -14.3||x>14.3||z>19.2||z< -28.7)return true;return world.obstacles.some(o=>Math.abs(x-o.x)<o.w/2+.36&&Math.abs(z-o.z)<o.d/2+.36);}
function simulate(dt){elapsed+=dt;let dx=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),dz=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0);const length=Math.hypot(dx,dz);if(length){dx/=length;dz/=length;const speed=crouching?2.0:3.5,step=speed*dt;const ox=state.x,oz=state.z;if(!blocked(state.x+dx*step,state.z))state.x+=dx*step;if(!blocked(state.x,state.z+dz*step))state.z+=dz*step;moved+=Math.hypot(state.x-ox,state.z-oz);body.rotation.y=Math.atan2(-dx,-dz);const walk=Math.sin(elapsed*11)*.35;legL.rotation.x=walk;legR.rotation.x=-walk;armL.rotation.x=-walk*.7;armR.rotation.x=walk*.7;}else{legL.rotation.x=legR.rotation.x=armL.rotation.x=armR.rotation.x=0;}body.scale.y=THREE.MathUtils.lerp(body.scale.y,crouching?.59:1,Math.min(1,dt*15));player.position.set(state.x,0,state.z);marker.position.y=crouching?2.1:3;
 const smoky=world.smokeZones.some(z=>Math.abs(state.x-z.x)<z.w/2&&Math.abs(state.z-z.z)<z.d/2);const hot=world.fires.some(f=>Math.hypot(state.x-f.x,state.z-f.z)<f.r+1.0);if(smoky){smokeSeconds+=dt;if(!crouching)standingSmoke+=dt;exposure+=dt*(crouching?3.2:9);}if(hot){fireSeconds+=dt;exposure+=dt*17;}exposure=Math.min(100,exposure);$('damage').style.opacity=hot?'.8':smoky?'.35':'0';if(state.z< -6&&Math.abs(state.x)>3.4)detour=true;
 if(exposure>=100){result(false);return;}if(state.z< -24.7&&Math.hypot(state.x-world.assembly.x,state.z-world.assembly.z)<2.5){complete();return;}
 if(uiTick<=0){updateUI(smoky,hot);uiTick=.12;}uiTick-=dt;
}
function updateUI(smoky=false,hot=false){$('time').textContent=formatTime(elapsed);$('exposure').innerHTML=Math.round(exposure)+'<small>/100</small>';$('exposure-bar').style.width=exposure+'%';$('progress').style.width=THREE.MathUtils.clamp((17-state.z)/44*100,0,100)+'%';$('stance').textContent=crouching?'↓ 낮은 자세로 이동 중':'서서 이동 중';$('crouch').textContent=crouching?'C  일어서기':'C  낮은 자세';if(hot){$('objective').textContent='불길에서 떨어지세요';$('mission-hint').textContent='화재 구역을 통과하지 말고 크게 우회하세요.';}else if(smoky){$('objective').textContent='연기 구간입니다 · 우회하세요';$('mission-hint').textContent='낮은 자세도 안전을 보장하지 않습니다.';}else if(state.z< -21){$('objective').textContent='옥외 집결지로 이동하세요';$('mission-hint').textContent='초록색 원 안으로 이동 · 재진입하지 않기';}else if(state.z<0){$('objective').textContent='불길을 우회해 비상구로';$('mission-hint').textContent='안내도의 연기 표시 밖으로 돌아갈 수 있습니다.';}else{$('objective').textContent='초록색 비상구를 찾아 탈출하세요';$('mission-hint').textContent='불길을 우회해 옥외 집결지까지 이동';}drawMap();}
function drawMap(){const c=$('minimap'),ctx=c.getContext('2d'),sx=6.0,sz=5.2;const x=v=>108+v*sx,z=v=>12+(v+28)*sz;ctx.clearRect(0,0,216,278);ctx.fillStyle='#0e1b22';ctx.fillRect(0,0,216,278);ctx.strokeStyle='#52626a';ctx.lineWidth=1;ctx.strokeRect(x(-15),z(-22),30*sx,42*sz);for(const o of world.obstacles){ctx.fillStyle='#4a5e65';ctx.fillRect(x(o.x-o.w/2),z(o.z-o.d/2),o.w*sx,Math.max(1,o.d*sz));}for(const s of world.smokeZones){ctx.fillStyle='#c7c6b648';ctx.fillRect(x(s.x-s.w/2),z(s.z-s.d/2),s.w*sx,s.d*sz);}world.fires.forEach(f=>{ctx.fillStyle='#fe7d48';ctx.beginPath();ctx.arc(x(f.x),z(f.z),f.r*sx,0,Math.PI*2);ctx.fill();});ctx.fillStyle='#72e4b6';ctx.fillRect(x(-2.8),z(-22.7),5.6*sx,7);ctx.beginPath();ctx.arc(x(0),z(-27),7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#9fe7c4';ctx.font='10px sans-serif';ctx.textAlign='left';ctx.fillText('집결지',x(2.2),z(-26.5));ctx.strokeStyle='#efffeb';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x(state.x),z(state.z),6,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#f5ffea';ctx.beginPath();ctx.arc(x(state.x),z(state.z),3,0,Math.PI*2);ctx.fill();}
const lookTarget=new THREE.Vector3(),desiredCamera=new THREE.Vector3(),desiredTarget=new THREE.Vector3();
function resize(){if(!renderer)return;renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}addEventListener('resize',resize);
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;const t=now/1000;world.update(t,dt);if(mode==='playing')simulate(dt);if(mode==='intro'){desiredTarget.set(-7,0,-4);desiredCamera.set(31,35,40);if(innerWidth<700){desiredTarget.set(0,0,-4);desiredCamera.set(36,45,43);}marker.visible=false;}else{const followX=innerWidth<700?state.x:state.x*.55;desiredTarget.set(followX,0,state.z-4);const zoom=innerWidth<700?1.14:1;desiredCamera.set(followX,23*zoom,state.z+19*zoom);marker.visible=true;}const lerp=mode==='intro'?.035:Math.min(1,dt*5);camera.position.lerp(desiredCamera,lerp);lookTarget.lerp(desiredTarget,lerp);camera.lookAt(lookTarget);ring.material.opacity=.7+Math.sin(t*3)*.15;if(now>toastUntil)$('toast').classList.remove('show');renderer.render(scene,camera);}
$('start').onclick=start;$('crouch').onclick=toggleCrouch;$('alert').onclick=raiseAlert;$('pause').onclick=pause;$('help').onclick=help;$('home').onclick=e=>{e.preventDefault();if(mode==='playing')pause();else home();};$('sound').onclick=()=>{muted=!muted;$('sound').textContent=muted?'소리 OFF':'소리 ON';$('sound').setAttribute('aria-label',muted?'소리 켜기':'소리 끄기');if(!muted)beep();};
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code)&&mode==='playing')e.preventDefault();if(e.code==='Tab'&&!$('modal').hidden){const focusable=[...$('dialog').querySelectorAll('button:not([disabled]):not([hidden]),a[href]')];if(focusable.length){const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===$('dialog'))){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}if(!e.repeat){if(e.code==='KeyC')toggleCrouch();if(e.code==='KeyE')raiseAlert();if(e.code==='Escape'){if(mode==='help'){$('help-close').click();}else pause();}}if(mode==='playing')keys.add(e.code);});addEventListener('keyup',e=>keys.delete(e.code));
function lostFocus(){keys.clear();if(mode==='playing')pause();}addEventListener('blur',lostFocus);document.addEventListener('visibilitychange',()=>{if(document.hidden)lostFocus();});
document.querySelectorAll('[data-key]').forEach(btn=>{btn.addEventListener('pointerdown',e=>{e.preventDefault();if(mode==='playing'){keys.add(btn.dataset.key);btn.setPointerCapture(e.pointerId);}});['pointerup','pointercancel','lostpointercapture'].forEach(type=>btn.addEventListener(type,()=>keys.delete(btn.dataset.key)));});
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();if(mode==='playing')pause();fatal(new Error('그래픽 연결이 중단되었습니다. 새로고침해 주세요.'));});
// Read-only diagnostic snapshot; no movement or result overrides.
window.lastExit=Object.freeze({snapshot:()=>({mode,position:{...state},elapsed,exposure,crouching,alerted,smokeSeconds,standingSmoke,fireSeconds,moved,quizCorrect,detour,sessions:counters.sessions,three:THREE.REVISION,drawCalls:renderer.info.render.calls}),map:()=>JSON.parse(JSON.stringify({obstacles:world.obstacles,fires:world.fires,smokeZones:world.smokeZones,exit:world.exit,assembly:world.assembly}))});
})();


